name: Telegram News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests openai pillow

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: "@jahantab_news"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot.py

      - name: Save sent links
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sent_links.txt

          if git diff --cached --quiet; then
            echo "No new sent links to save."
          else
            git commit -m "Update sent news links"
            git push
          fi
